### ISSUE TITLE
Crashing when trying to pick up modded mobs

### ISSUE THREAD

**Issue by PurpleHel** [vladaviedov/gitbm#10]
**Describe the bug**
Crashing when trying to pick up modded mobs-seen with MCA villager and alex's mobs racoon. didn't crash when picking up vanilla sheep.

**How To Reproduce**
right click modded mob with bucket

**Screenshots**

**Logs**
https://crashy.net/pOOurjrl5y2MR7rY4fh1
https://pastebin.com/ceFSV5yS (same log, but the auto uploaded to crashy version seemed too short, so I manually uploaded to pastebin.)

**Versions**
 - Minecraft: 1.19.2
 - Forge: 43.1.15
 - Mod: 4.1.1

**Additional info**
Add any additional information about the problem here.

**Comment by PurpleHel** [comment]
Awesome, thanks! This mod is so great, it's on my 'I don't move to a new version until this mod is updated for it' list, along with quark and a few other mods! Thanks for making it!

**Comment by vladaviedov** [comment]
I'm glad you're enjoying the mod!
