### ISSUE TITLE
Crash when using MCA Reborn Hero Villager

### ISSUE THREAD

**Issue by keepinitreal247** [vladaviedov/gitbm#5]
So when I get a hero villager from a lucky lock and I want to put him in a bucket when I attempt to the game immediately crashes.
 

Debug Log Since there doesn't seem to be a crash log????
https://gist.github.com/keepinitreal247/501c41f169361f6d246d39a865b0e81e

**Comment by vladaviedov** [comment]
This seems to be an issue with the MCA mod:

`[11Jun2022 10:06:40.951] [Render thread/ERROR] [net.minecraft.client.main.Main/]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "mca.entity.VillagerLike.asEntity()" because "this.villager" is null.`
